name: npdart
description: A minimal game engine for visual novels.
version: 0.2.0
repository: "https://github.com/peaashmeter/npdart" 

environment:
  sdk: ^3.0.0


dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.7.0
  path_provider: ^2.0.11
  equatable: ^2.0.5
  intl: ^0.18.1
  async: ^2.11.0
  just_audio: ^0.9.36
  just_audio_windows: ^0.2.0
  just_audio_mpv: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


